<div class="row">
    <div class="col-md-12">
        <h1>Exclusão de Tarefa</h1>
        <p>Você tem certeza que deseja excluir essa Tarefa?<p>
        <?php $action = $this->url('task/resource', array('id' => $this->id));?>
        <form action="<?=$action?>" method="post" name="Confirm" id="Confirm">
            <input type="hidden" name="_method" value="delete">
            <input class="btn btn-danger" name="confirm" type="submit" id="confirm" value="Sim">
            <a class="btn btn-primary" href="<?=$this->url('task');?>">Não</a>
        </form>
    </div>
</div>