<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */

$config = require 'config/application.config.php';
$config['module_listener_options']['config_glob_paths'] = array('config/autoload/{,*.}{global,local,test}.php');

return $config;
